### ISSUE TITLE
Additional Kestrel dimension: LibUV

### ISSUE THREAD

**Issue by et1975** [TheAngryByrd/dotnet-web-benchmarks#16]
Apparently dotnet 2.0 adds managed sockets implementation (which might even be the default?). Would be interesting to see the benchmarks updated to 2.0 with additional LibUV/managed sockets implementation.

**Comment by TheAngryByrd** [comment]
That would be pretty good! Marked as `help wanted` if anyone wants to submit a PR.

**Comment by et1975** [comment]
I think with LibUV being dropped we can close this.
