### ISSUE TITLE
Docker build is taking too long and broken

### ISSUE THREAD

**Issue by et1975** [TheAngryByrd/dotnet-web-benchmarks#2]
How about rebasing it on https://hub.docker.com/r/microsoft/dotnet/, at any rate something with mono pre-built?

**Comment by TheAngryByrd** [comment]
https://github.com/TheAngryByrd/dotnet-web-benchmarks/pull/1 started compiling mono with llvm built in.  I should probably split it into it's own dockerfile for people to test LLVM.

**Comment by TheAngryByrd** [comment]
I removed the LLVM test and went back to normal mono.  Re-open if this is still a problem.
